---
title: "FDA Tables using rtable package"
format: 
  html:
    toc: true
    code-fold: true
editor: visual
---

## **FDA Table 1**

Note: this table is taken from README.MD

```{r}
#| warning: false
library(falcon)
adsl <- random.cdisc.data::cadsl
make_table_02(
  df = adsl,
  vars = c("SEX", "AGE", "RACE"),
  lbl_vars = c("Sex", "Age, years", "Race")
) 
# |> as_html(class_table = "table", class_tr = "column")
```

## **FDA Table 2**

```{r}
#| warning: false
# Load Libraries & Data
library(falcon)
library(dplyr)

adsl <- random.cdisc.data::cadsl
advs <- random.cdisc.data::cadvs

# Pre-Processing - Add any variables needed in your table to df
adsl <- adsl %>%
  mutate(AGEGR1 = as.factor(case_when(
    AGE >= 17 & AGE < 65 ~ ">=17 to <65",
    AGE >= 65 ~ ">=65",
    AGE >= 65 & AGE < 75 ~ ">=65 to <75",
    AGE >= 75 ~ ">=75"
  )))

advs <- advs %>%
  filter(AVISIT == "BASELINE", VSTESTCD == "TEMP") %>%
  select("USUBJID", "AVAL")

anl <- left_join(adsl, advs, by = "USUBJID")

# Output Table
make_table_02(
  df = anl,
  vars = c("SEX", "AGE", "AGEGR1", "RACE", "ETHNIC", "COUNTRY", "AVAL"),
  lbl_vars = c(
    "Sex", "Age, years", "Age Group, years", "Race", "Ethnicity",
    "Country of Participation", "Baseline Temperature (C)"
  )
)
```

## **FDA Table 3**

```{r}
#| warning: false
# Load Libraries & Data
library(dplyr)
library(falcon)

adsl <- random.cdisc.data::cadsl

# Pre-Processing - Add all required screening variables are in df
set.seed(1)
adsl <- random.cdisc.data::cadsl
adsl$RANDDT[sample(seq_len(nrow(adsl)), 100)] <- NA
adsl <- adsl %>%
  mutate(
    ENRLDT = RANDDT,
    SCRNFL = "Y",
    SCRNFRS = factor(sample(
      c("Inclusion/exclusion criteria not met", "Patient noncompliance", "Consent withdrawn", "Other"),
      size = nrow(adsl), replace = TRUE
    ), levels = c("Inclusion/exclusion criteria not met", "Patient noncompliance", "Consent withdrawn", "Other")),
    SCRNFAILFL = ifelse(is.na(ENRLDT), "Y", "N")
  )
adsl$SCRNFRS[adsl$SCRNFL == "N" | !is.na(adsl$ENRLDT)] <- NA

# Output Table
make_table_03(df = adsl, scrnfl_var = "SCRNFL", scrnfailfl_var = "SCRNFAILFL", scrnfail_var = "SCRNFRS")
```

## **FDA Table 4**

```{r}
# Load Libraries & Data
library(falcon)
library(dplyr)

adsl <- random.cdisc.data::cadsl %>%
  mutate(test = rbinom(400, 1, 0.5)) %>%
  mutate(
    RANDFL = ifelse(test == 0, "N", "Y"),
    PPROTFL = ifelse(test == 0, "N", "Y"),
    DCSREAS = if_else(DCSREAS %in% c(
      "ADVERSE EVENT", "LACK OF EFFICACY", "PROTOCOL VIOLATION",
      "DEATH", "WITHDRAWAL BY PARENT/GUARDIAN"
    ), DCSREAS, "OTHER")
  ) %>%
  mutate(DCTREAS = DCSREAS)

# Output Table
risk_diff <- list(arm_x = "B: Placebo", arm_y = "A: Drug X") # optional
tbl <- make_table_04(
  df = adsl, pop_vars = c("RANDFL", "ITTFL", "SAFFL", "PPROTFL"),
  lbl_pop_vars = c("Patients randomized", "ITT/mITT population", "Safety population", "Per-protocol population"),
  risk_diff = risk_diff
)
tbl
```

## **FDA Table 5**

```{r}
# Load Libraries & Data
library(falcon)

adsl <- random.cdisc.data::cadsl

# Output Table
risk_diff <- list(arm_x = "B: Placebo", arm_y = "A: Drug X") # optional
make_table_05(df = adsl, risk_diff = risk_diff)
```

## **FDA Table 6**

```{r}
# Load Libraries & Data
library(falcon)

adsl <- random.cdisc.data::cadsl
adae <- random.cdisc.data::cadae

# Output Table
risk_diff <- list(arm_x = "B: Placebo", arm_y = "A: Drug X") # optional
make_table_06(adae = adae, alt_counts_df = adsl, risk_diff = risk_diff)
```

## **FDA Table 7**

```{r}
# Load Libraries & Data
library(falcon)

adsl <- random.cdisc.data::cadsl
adae <- random.cdisc.data::cadae

# Pre-Processing - Ensure all required variables are present in adae
set.seed(1)
adae$TRTEMFL <- ifelse(adae$USUBJID %in% sample(adsl$USUBJID, size = as.integer(nrow(adsl) / 3)), "N", "Y")

# Output Table
risk_diff <- list(arm_x = "B: Placebo", arm_y = "A: Drug X") # optional
make_table_07(adae = adae, alt_counts_df = adsl, risk_diff = risk_diff)
```

## **FDA Table 8**

```{r}
# Load Libraries & Data
library(falcon)

adae <- random.cdisc.data::cadae
adex <- random.cdisc.data::cadex

# Output Table
make_table_08(adae = adae, adex = adex)
```

## **FDA Table 9**

```{r}
# Load Libraries & Data
library(falcon)

adsl <- random.cdisc.data::cadsl
adae <- random.cdisc.data::cadae

# Select Preferred Term Variable
pref_var <- "AEDECOD"

# Output Table
risk_diff <- list(arm_x = "B: Placebo", arm_y = "A: Drug X") # optional
make_table_09(adae = adae, alt_counts_df = adsl, pref_var = pref_var, risk_diff = risk_diff)
```

## **FDA Table 10**

```{r}
# Load Libraries & Data
library(dplyr)
library(falcon)

adsl <- random.cdisc.data::cadsl
adae <- random.cdisc.data::cadae

# Pre-Processing - Ensure required variables fmqsc_var and fmqnam_var exist in adae
set.seed(1)
adae <- adae %>%
  rename(FMQ01SC = SMQ01SC) %>%
  mutate(
    AESER = sample(c("Y", "N"), size = nrow(adae), replace = TRUE),
    FMQ01NAM = sample(c("FMQ1", "FMQ2", "FMQ3"), size = nrow(adae), replace = TRUE)
  )
adae$FMQ01SC[is.na(adae$FMQ01SC)] <- "NARROW"

# Output Table
risk_diff <- list(arm_x = "B: Placebo", arm_y = "A: Drug X") # optional
make_table_10(adae = adae, alt_counts_df = adsl, risk_diff = risk_diff)
```

## **FDA Table 11**

```{r}
# Load Libraries & Data
library(dplyr)
library(falcon)

adsl <- random.cdisc.data::cadsl
adae <- random.cdisc.data::cadae

# Pre-Processing - Ensure required variables fmqsc_var and fmqnam_var exist in adae
set.seed(1)
adae <- adae %>%
  rename(FMQ01SC = SMQ01SC) %>%
  mutate(
    AESER = sample(c("Y", "N"), size = nrow(adae), replace = TRUE),
    FMQ01NAM = sample(c("FMQ1", "FMQ2", "FMQ3"), size = nrow(adae), replace = TRUE)
  )
adae$DCSREAS[is.na(adae$DCSREAS)] <- "ADVERSE EVENT"
adae$FMQ01SC[is.na(adae$FMQ01SC)] <- "NARROW"

# Output Table
risk_diff <- list(arm_x = "B: Placebo", arm_y = "A: Drug X") # optional
make_table_11(adae = adae, alt_counts_df = adsl, risk_diff = risk_diff)
```

## **FDA Table 12**

```{r}
# Load Libraries & Data
library(falcon)

adsl <- random.cdisc.data::cadsl
adae <- random.cdisc.data::cadae

# Pre-Processing - Ensure required variable DCSREAS exist in adae
adae$DCSREAS[is.na(adae$DCSREAS)] <- "ADVERSE EVENT"

# Select Preferred Term Variable
pref_var <- "AEDECOD"

# Output Table
risk_diff <- list(arm_x = "B: Placebo", arm_y = "A: Drug X") # optional
make_table_12(adae = adae, alt_counts_df = adsl, pref_var = pref_var, risk_diff = risk_diff)
```

## **FDA Table 13**

```{r}
# Load Libraries & Data
library(falcon)

adsl <- random.cdisc.data::cadsl
adae <- random.cdisc.data::cadae

# Select Preferred Term Variable
pref_var <- "AEDECOD"

# Select Minimum Frequency (%)
min_freq <- 0.40

# Output Table
risk_diff <- list(arm_x = "B: Placebo", arm_y = "A: Drug X") # optional
make_table_13(adae = adae, alt_counts_df = adsl, pref_var = pref_var, min_freq = min_freq, risk_diff = risk_diff)
```

## **FDA Table 14**

```{r}
# Load Libraries & Data
library(falcon)

adae <- random.cdisc.data::cadae

# Pre-Processing - Ensure required variables FMQ01SC and FMQ01NAM exist in adae
adae <- dplyr::rename(adae, FMQ01SC = SMQ01SC, FMQ01NAM = SMQ01NAM)
levels(adae$FMQ01SC) <- c("BROAD", "NARROW")
adae$FMQ01SC[is.na(adae$FMQ01SC)] <- "NARROW"

# Output Table
risk_diff <- list(arm_x = "B: Placebo", arm_y = "A: Drug X") # optional
make_table_14(adae = adae, risk_diff = risk_diff)
```

## **FDA Table 15**

```{r}
# Load Libraries & Data
library(falcon)

adsl <- random.cdisc.data::cadsl
adae <- random.cdisc.data::cadae

# Pre-Processing - Ensure required variables FMQ01SC and FMQ01NAM exist in adae
set.seed(1)
adae <- dplyr::rename(adae, FMQ01SC = SMQ01SC, FMQ01NAM = SMQ01NAM)
levels(adae$FMQ01SC) <- c("BROAD", "NARROW")
adae$FMQ01SC[is.na(adae$FMQ01SC)] <- "NARROW"
adae$FMQ01NAM <- factor(adae$FMQ01NAM, levels = c(unique(adae$FMQ01NAM), "Erectile Dysfunction", "Gynecomastia"))
adae$FMQ01NAM[adae$SEX == "M"] <- as.factor(
  sample(c("Erectile Dysfunction", "Gynecomastia"), sum(adae$SEX == "M"), replace = TRUE)
)

# Output Table
risk_diff <- list(arm_x = "B: Placebo", arm_y = "A: Drug X")
make_table_15(adae = adae, alt_counts_df = adsl, risk_diff = risk_diff)
```

## **FDA Table 16**

```{r}
# Load Libraries & Data
library(falcon)

adsl <- random.cdisc.data::cadsl
adae <- random.cdisc.data::cadae

# Pre-Processing - Ensure required variables FMQ01SC and FMQ01NAM exist in adae
set.seed(1)
adae <- dplyr::rename(adae, FMQ01SC = SMQ01SC, FMQ01NAM = SMQ01NAM)
levels(adae$FMQ01SC) <- c("BROAD", "NARROW")
adae$FMQ01SC[is.na(adae$FMQ01SC)] <- "NARROW"
adae$FMQ01NAM <- factor(adae$FMQ01NAM, levels = c(unique(adae$FMQ01NAM), "Erectile Dysfunction", "Gynecomastia"))
adae$FMQ01NAM[adae$SEX == "M"] <- as.factor(
  sample(c("Erectile Dysfunction", "Gynecomastia"), sum(adae$SEX == "M"), replace = TRUE)
)

# Output Table
risk_diff <- list(arm_x = "B: Placebo", arm_y = "A: Drug X")
make_table_16(adae = adae, alt_counts_df = adsl, risk_diff = risk_diff)
```

## **FDA Table 17**

```{r}
# Load Libraries & Data
library(falcon)

adsl <- random.cdisc.data::cadsl
adae <- random.cdisc.data::cadae

# Pre-Processing - Ensure required variables FMQ01SC and FMQ01NAM exist in adae
set.seed(1)
adae <- dplyr::rename(adae, FMQ01SC = SMQ01SC, FMQ01NAM = SMQ01NAM)
levels(adae$FMQ01SC) <- c("BROAD", "NARROW")
adae$FMQ01SC[is.na(adae$FMQ01SC)] <- "NARROW"
adae$FMQ01NAM <- factor(adae$FMQ01NAM, levels = c(
  unique(adae$FMQ01NAM), "Abnormal Uterine Bleeding", "Amenorrhea",
  "Bacterial Vaginosis", "Decreased Menstrual Bleeding"
))
adae$FMQ01NAM[adae$SEX == "F"] <- as.factor(
  sample(c(
    "Abnormal Uterine Bleeding", "Amenorrhea",
    "Bacterial Vaginosis", "Decreased Menstrual Bleeding"
  ), sum(adae$SEX == "F"), replace = TRUE)
)

# Output Table
risk_diff <- list(arm_x = "B: Placebo", arm_y = "A: Drug X")
make_table_17(adae = adae, alt_counts_df = adsl, risk_diff = risk_diff)
```

## **FDA Table 18**

```{r}
# Load Libraries & Data
library(falcon)

adsl <- random.cdisc.data::cadsl
adae <- random.cdisc.data::cadae

# Pre-Processing - Ensure required variables FMQ01SC and FMQ01NAM exist in adae
set.seed(1)
adae <- dplyr::rename(adae, FMQ01SC = SMQ01SC, FMQ01NAM = SMQ01NAM)
levels(adae$FMQ01SC) <- c("BROAD", "NARROW")
adae$FMQ01SC[is.na(adae$FMQ01SC)] <- "NARROW"
adae$FMQ01NAM <- factor(adae$FMQ01NAM, levels = c(
  unique(adae$FMQ01NAM), "Abnormal Uterine Bleeding", "Amenorrhea",
  "Bacterial Vaginosis", "Decreased Menstrual Bleeding"
))
adae$FMQ01NAM[adae$SEX == "F"] <- as.factor(
  sample(c(
    "Abnormal Uterine Bleeding", "Amenorrhea",
    "Bacterial Vaginosis", "Decreased Menstrual Bleeding"
  ), sum(adae$SEX == "F"), replace = TRUE)
)

# Output Table
risk_diff <- list(arm_x = "B: Placebo", arm_y = "A: Drug X")
make_table_18(adae = adae, alt_counts_df = adsl, risk_diff = risk_diff)
```

## **FDA Table 20**

```{r}
# Load Libraries & Data
library(falcon)

adsl <- random.cdisc.data::cadsl
adae <- random.cdisc.data::cadae

# Pre-Processing - Add/create any required variables in adae
set.seed(1)
adae$AESIFL <- ifelse(adae$AESOC %in% c("cl A", "cl D"), "Y", "N")
adae$AELABFL <- sample(c("Y", "N"), nrow(adae), replace = TRUE)

# Select Preferred Term Variable
pref_var <- "AEDECOD"

# Output Table
risk_diff <- list(arm_x = "B: Placebo", arm_y = "A: Drug X") # optional
make_table_20(
  adae = adae, alt_counts_df = adsl, pref_var = pref_var, aesifl_var = "AESIFL",
  aelabfl_var = "AELABFL", risk_diff = risk_diff
)
```

## **FDA Table 21**

```{r}
# Load Libraries & Data
library(dplyr)
library(falcon)

adsl <- random.cdisc.data::cadsl %>%
  mutate(AGEGR1 = as.factor(case_when(
    AGE >= 17 & AGE < 65 ~ ">=17 to <65",
    AGE >= 65 ~ ">=65",
    AGE >= 65 & AGE < 75 ~ ">=65 to <75",
    AGE >= 75 ~ ">=75"
  )) %>% formatters::with_label("Age Group, years")) %>%
  formatters::var_relabel(
    AGE = "Age, years"
  )

adae <- random.cdisc.data::cadae
adae$ASER <- adae$AESER

df <- left_join(adsl, adae, by = intersect(names(adsl), names(adae)))

# Output Table
make_table_21(df = df, alt_counts_df = adsl, denom = "N_s")
```

## **FDA Table 22**

```{r}
# Load Libraries & Data
library(dplyr)
library(falcon)

adsl <- random.cdisc.data::cadsl %>%
  mutate(AGEGR1 = as.factor(case_when(
    AGE >= 17 & AGE < 65 ~ ">=17 to <65",
    AGE >= 65 ~ ">=65",
    AGE >= 65 & AGE < 75 ~ ">=65 to <75",
    AGE >= 75 ~ ">=75"
  )) %>% formatters::with_label("Age Group, years")) %>%
  formatters::var_relabel(AGE = "Age, years")

adae <- random.cdisc.data::cadae

df <- left_join(adsl, adae, by = intersect(names(adsl), names(adae)))

# Output Table
make_table_22(df = df, alt_counts_df = adsl, denom = "N_s")
```

## **FDA Table 32**

```{r}
# Load Libraries & Data
library(falcon)

adsl <- random.cdisc.data::cadsl
advs <- random.cdisc.data::cadvs

# Output Table
risk_diff <- list(arm_x = "B: Placebo", arm_y = "A: Drug X") # optional
make_table_32(advs = advs, alt_counts_df = adsl, risk_diff = risk_diff)
```

## **FDA Table 33**

```{r}
# Load Libraries & Data
library(falcon)

adsl <- random.cdisc.data::cadsl
advs <- random.cdisc.data::cadvs
advs$AVAL <- advs$AVAL - 100

# Output Table
risk_diff <- list(arm_x = "B: Placebo", arm_y = "A: Drug X") # optional
make_table_33(advs = advs, alt_counts_df = adsl, risk_diff = risk_diff)
```

## **FDA Table 34**

```{r}
# Load Libraries & Data
library(dplyr)
library(falcon)

adsl <- random.cdisc.data::cadsl
adae <- random.cdisc.data::cadae

# Pre-Processing - Ensure required variables fmqsc_var and fmqnam_var exist in adae
set.seed(1)
adae <- adae %>%
  rename(FMQ01SC = SMQ01SC) %>%
  mutate(
    AESER = sample(c("Y", "N"), size = nrow(adae), replace = TRUE),
    FMQ01NAM = sample(c("FMQ1", "FMQ2", "FMQ3"), size = nrow(adae), replace = TRUE)
  )
adae$FMQ01SC[is.na(adae$FMQ01SC)] <- "NARROW"

# Select Preferred Term Variable
pref_var <- "AEDECOD"

# Output Table
risk_diff <- list(arm_x = "B: Placebo", arm_y = "A: Drug X") # optional
make_table_34(adae = adae, alt_counts_df = adsl, pref_var = pref_var, risk_diff = risk_diff)
```

## **FDA Table 35**

```{r}
# Load Libraries & Data
library(random.cdisc.data)
library(falcon)

adsl <- random.cdisc.data::cadsl
adae <- random.cdisc.data::cadae

# Output Table
risk_diff <- list(arm_x = "B: Placebo", arm_y = "A: Drug X") # optional
make_table_35(adae = adae, alt_counts_df = adsl, risk_diff = risk_diff)
```

## **FDA Table 36**

```{r}
# Load Libraries & Data
library(random.cdisc.data)
library(falcon)

adsl <- random.cdisc.data::cadsl
adae <- random.cdisc.data::cadae

# Output Table
risk_diff <- list(arm_x = "B: Placebo", arm_y = "A: Drug X") # optional
make_table_36(adae = adae, alt_counts_df = adsl, risk_diff = risk_diff)
```
